name: Run gtest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up NASM
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends nasm
    - name: run test
      run: make -s test
    - name: upload test logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Test-Logs
        path: build/tests/Testing/Temporary/LastTest.log